version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_carforme
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5431:5432"
    restart: always
  app:
    build: .
    container_name: CarForMe_App
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    restart: always