CREATE TABLE tb_cars(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    brand VARCHAR(100),
    body VARCHAR(100),
    manufactureYear INTEGER,
    valuecar DOUBLE PRECISION,
    consume DOUBLE PRECISION,
    description VARCHAR(255),
    imgurl VARCHAR(255)
);